### ISSUE TITLE
Enhance test to count the features from the ESRI response format.

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-wms13-dgiwg#11]
[1] https://externaltest.dev.geocloud.com/server/services/PuertoRicoRaster/MapServer/WMSServer?request=GetCapabilities&service=WMS

With reference: https://github.com/opengeospatial/ets-wms13-nsg/issues/16

The test **`"wms Get Feature Info Feature Count With Value Of One"`** and **"`wms Get Feature Info Feature Count With Value Of Ten`"** need to update to count the feature from the ESRI response.

**Comment by keshavnangare** [comment]
Fixed this issue with commit 76e4381cec554dc0d9a13b90e37a0fee837d2a14 [PR: #12]

Closes https://github.com/opengeospatial/ets-wms13-nsg/issues/16.

**Comment by lgoltz** [comment]
Unfortunately the service is not available. I've added some tests and made parsing of feature members more robust (allow GML 3.2).

**Comment by dstenger** [comment]
Testing is not possible as no test service available. However, implementation looks good.
